# Generated by Django 2.2.3 on 2019-07-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_user_id', models.BigIntegerField()),
                ('fatsecret_oauth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('fatsecret_oauth_token_secret', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
