# Generated by Django 2.2.3 on 2019-07-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat_secret_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='bot_user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
