# Generated by Django 2.2.3 on 2019-07-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat_secret_api', '0002_auto_20190723_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='fatsecret_account',
            field=models.CharField(choices=[('NO', 'NO'), ('NEW', 'NEW'), ('OLD', 'OLD')], default='NO', max_length=3),
        ),
    ]
