# Generated by Django 2.2.3 on 2019-07-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fat_secret_api', '0003_botuser_fatsecret_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='fs_request_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='fs_request_token_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
