# Generated by Django 2.2.3 on 2019-07-27 11:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_phone_auth_try',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phones_changed_at_auth',
            field=models.IntegerField(default=0),
        ),
    ]
