# Generated by Django 2.2.3 on 2019-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20190727_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
