# Generated by Django 2.2.3 on 2019-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_botuser_phone_number_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
