# Generated by Django 2.2.3 on 2019-07-27 12:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_botuser_phone_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', unique=True),
        ),
    ]
