# Generated by Django 2.2.3 on 2019-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_auto_20190727_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='codes_changed_at_auth',
            field=models.IntegerField(default=0),
        ),
    ]
