# Generated by Django 2.2.3 on 2019-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0006_botuser_codes_changed_at_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='last_phone_auth_try',
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_code_confirmation_try',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_phone_change_try',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
