# Generated by Django 2.2.3 on 2019-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0007_auto_20190729_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='bmi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
